### ISSUE TITLE
Run main process as user nginx or nobody

### ISSUE THREAD

**Issue by t-book** [GeoNode/nginx-docker#7]
I'd like to suggest running the main Nginx process as non-root:

```
toni@base:~/dev/github/csgis_geonode/geonode$ docker exec nginx4geonode ps
PID   USER     TIME  COMMAND
    1 root      0:00 nginx: master process nginx -g daemon off;
```

the same for the lets encrypt container

```
toni@base:~/dev/github/csgis_geonode/geonode$ docker exec letsencrypt4geonode ps
PID   USER     TIME  COMMAND
    1 root      0:00 {docker-entrypoi} /bin/sh ./docker-entrypoint.sh /bin/sh -c /usr/sbin/crond -f
   10 root      0:00 sleep 30
   11 root      0:00 ps

```

Most likely all it takes is to add  `USER NGINX` to the Dockerfile and  make the cert directories rw for user nginx

**Comment by t-book** [comment]
After thinking about it for a while it might not be that easy as:
- geonode docker is sharing the letsencrypt service with SPC_geonode
- Ports below 1024 might not be allowed for non-root users, hence most likely it would be needed to use a port above 1024 inside the container.

What is too much work by now for me.

I will close here and will most likely cut the permissions of nginx with an apparmor profile similar to:

**docker-nginx**
```
#include <tunables/global>

profile docker-nginx-sample flags=(attach_disconnected,mediate_deleted) {
  #include <abstractions/base>
  network inet tcp,
  network inet udp,
  network inet icmp,
  deny network raw,
  deny network packet,
  file,
  umount,
  deny /bin/** wl,
  deny /boot/** wl,
  deny /dev/** wl,
  deny /home/** wl,
  deny /lib/** wl,
  deny /lib64/** wl,
  deny /media/** wl,
  deny /mnt/** wl,
  deny /opt/** wl,
  deny /proc/** wl,
  deny /root/** wl,
  deny /sbin/** wl,
  deny /srv/** wl,
  deny /tmp/** wl,
  deny /sys/** wl,
  deny /usr/** wl,
  audit /** w,
  /var/run/nginx.pid w,
  /usr/sbin/nginx ix,
  deny /bin/dash mrwklx,
  deny /bin/sh mrwklx,
  deny /usr/bin/top mrwklx,
  capability chown,
  capability dac_override,
  capability setuid,
  capability setgid,
  capability net_bind_service,
  deny @{PROC}/* w,   # deny write for all files directly in /proc (not in a subdir)
  deny @{PROC}/{[^1-9],[^1-9][^0-9],[^1-9s][^0-9y][^0-9s],[^1-9][^0-9][^0-9][^0-9]*}/** w,
  deny @{PROC}/sys/[^k]** w,  # deny /proc/sys except /proc/sys/k* (effectively /proc/sys/kernel)
  deny @{PROC}/sys/kernel/{?,??,[^s][^h][^m]**} w,  # deny everything except shm* in /proc/sys/kernel/
  deny @{PROC}/sysrq-trigger rwklx,
  deny @{PROC}/mem rwklx,
  deny @{PROC}/kmem rwklx,
  deny @{PROC}/kcore rwklx,
  deny mount,
  deny /sys/[^f]*/** wklx,
  deny /sys/f[^s]*/** wklx,
  deny /sys/fs/[^c]*/** wklx,
  deny /sys/fs/c[^g]*/** wklx,
  deny /sys/fs/cg[^r]*/** wklx,
  deny /sys/firmware/efi/efivars/** rwklx,
  deny /sys/kernel/security/** rwklx,
}

```

Which one can install with `sudo apparmor_parser -r -W docker-nginx` and reference in docker-compose.yml like:

```
  geonode:
    image: geonode/nginx:3.x
    build: ./scripts/docker/nginx/
    container_name: nginx4${COMPOSE_PROJECT_NAME}
    environment:
      - HTTPS_HOST=${HTTPS_HOST}
      - HTTP_HOST=${HTTP_HOST}
      - HTTPS_PORT=${HTTPS_PORT}
      - HTTP_PORT=${HTTP_PORT}
      - LETSENCRYPT_MODE=${LETSENCRYPT_MODE}
      - RESOLVER=127.0.0.11
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - nginx-confd:/etc/nginx
      - nginx-certificates:/geonode-certificates
      - statics:/mnt/volumes/statics
    restart: on-failure
    security_opt:
      - apparmor:docker-nginx # the security profile
```

As a test login into the nginx container and `ping 8.8.8.8`

https://docs.docker.com/engine/security/apparmor/
